### ISSUE TITLE
error in running the project on android studio 3

### ISSUE THREAD

**Issue by maamjadi** [BME-MIT-IET/eng1-iet-2018#2]
guys I am trying to run the project on android studio 3 and so far I wasn't successful to do so.
as the result of my research I found out that we need to change the followings in app lever build.gradle:

1. removing `apply plugin: 'com.neenbedankt.android-apt'` as android-apt is no longer is needed in this version
2. in `apt "com.google.dagger:dagger-compiler:${libs.dagger}"` change the **apt** to **annotationProcessor**
3. for the butterknife after the line: `compile 'com.jakewharton:butterknife:7.0.1'` we need to add `annotationProcessor 'com.jakewharton:butterknife-compiler:8.7.0'`

but after all these steps I still get the error as the following:
`Error:java.lang.RuntimeException: Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.`

does anybody have any idea?

**Comment by alialsaeedi19** [comment]
I'm running it on android studio 3 without changing anything and it is working. Maybe try to download the app again and don't change anything it might work.

**Comment by amra12** [comment]
@maamjadi Amin I had the same problem actually as you because I had the Android version 3.0.0.1. go here : In the first Picture you can go to Check for updates and update your version to the latest Android Version : 
<img width="479" alt="screen shot 2018-04-26 at 11 24 57 pm" src="https://user-images.githubusercontent.com/23418043/39332894-2b6c97c6-49a9-11e8-84a4-eab7f6485633.png">

After you update in the build.gradle change the com.android.tools.build.gradle:3.1.0 to this one on the picture 2.3.2 , and when it asks to update it to this 3.1.0 or 3.1.1 dont do it 
![messages image 3582505321](https://user-images.githubusercontent.com/23418043/39332951-5da937ee-49a9-11e8-9a63-b140f5e1064b.jpeg)

![messages image 3488488049](https://user-images.githubusercontent.com/23418043/39332945-5919162c-49a9-11e8-8164-55dfcbfb5f90.jpeg)

**Comment by alialsaeedi19** [comment]
@wschenbuer Be sure you have followed the provided steps above from Amra for android version and for the grade version. If it still not working let us know.

**Comment by wschenbuer** [comment]
@alialsaeedi19  Thanks, i have solved problem by following steps which @maamjadi  uploaded

**Comment by maamjadi** [comment]
@alialsaeedi19 @amra12 thanks guys everything is working now
